# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 13.0
rebel_module_groups: []
repo_description:
  Addons for the management of multi company instances as well as inter company
  communication.
repo_name: Multi Company
repo_slug: multi-company
travis_apt_packages: []
travis_apt_sources: []
