[project]
name = "odoo-addons-oca-multi-company"
version = "18.0.20250221.1"
dependencies = [
    "odoo-addon-mail_template_multi_company==18.0.*",
    "odoo-addon-res_company_code==18.0.*",
    "odoo-addon-res_company_search_view==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
